[[redirects]]
  from = "/"
  to = "/src/index.html"
  status = 200

[[redirects]]
  from = "/users"
  to = "/src/index.html"
  status = 200

[[redirects]]
  from = "/add"
  to = "/src/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/src/index.html"
  status = 400
